[project]
name = "joingroupverify-bot"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "aiohttp>=3.12.15",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
]
